language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
  - secure: FdVX/heVy9uFrezyQJYOlKx2cpydc41NssFVrbQd1DH+XMU08zdpimCF6QyW6Qt88XOhlYaHL2fyYOCj8NdwQw5FPbHMl0YY8tJVn5Rce99aPKGFogyBnhFusiGnD+sXHrhKaLxgp6Rz0S/sQE3YzLSz+2wI1yrnVg/jq+IsR6LF5TvvrTn3QyCYMkoWWicH0lrnN//P2qZN1fdKTZFCdLKxcJmfcBsY5JtZ6YdxphL9alDck+ArtwKBGVfnnw1C3VJbhpifvbsxtEUBC4GI0Goek3NJ3cBOJV/tolkWYkshny6DANweGETFHYbKnhxnCECQwwgk+bmrcGU+gEogvERpaab9owxwHeG1tFDl1AtX5oALmmJpoCN4lrbEQb746q3rX4EY9ELyHkVNx1Wcb8cYJlvSczaZ33UsZA22ZFR+wssmzjIpYZmVM6Zt5l+4Qjr8hanx+USVkTlNn23DYbtL+Ot4l/gS29mEPQVUznaZOmSfuoyUJeFiWMWEkeLN6AU+RIpCg593wPpFCf4DAzx8poydO6oLUnYflbCjrZ/hzE2g9dkymP29N4wiEoSE9yMO+FZZjpNvNAzkbC4xJVzHgAj47a8qDsGtFgHb15XitZ3Z+3/ArXpH1ABBrt9wzvOZQT3KAE4YfblwmPiO7fXSU4zMR3MqbRt08AQPtLs=
  - secure: YXJTsL0OxZhRlpW7uqvNCmo/miPYeeCWp9rH8B129Fr0/qNGqpxUl/fNHoDMtxq4zU1+Nl2M4y8zO3pJ3Cmj/4u6+qS3gGOSBG1lKQ2VU3BI3oh57VEWcoyMvO3mv0XqUndFW2O9UyGmor6hsDUhbtp8nJYI+0s3jxNcZxpTNivZy5hEybpUdBMoqpq9iKaA2gUCDIKzd3JGZiuhh45JYoppiG7HfJtyUoTF+o30oTARyDOYXNoeiBWY+dPegv6SJ6KOyRNbOLi5+4EBingAWVlhi7RUHOn1xPfSyd4737RXgZOthCwAaGEDY274m1eFHfMaM2hH5qs15sRIPAjkwgcZjH5MW6FHtsxln/Mx0LG7D7BNvpoGfSa8UHdEvyjt0IIFsuD+PBpCb7bEgSCgRWNbSeRk6vvD5AfxhOvdHy8KL9sLQRNDqYv6YaeGXpgENdZLwxdmXNu3FSn0Sf5ldq3BfiOMzze85uzlUqi1i09r/4OmyTYZuDJUA0/NWAuLd7qXB22DfArBz3OOI4w0+WmqnegLYyGFMIEBnR8FPK/EMnU5XyJONwKdoZgbgAk+g5OF8qlH+bJKVOrVE6hW/DritofiZlXNQzwAdn1b5eCmtROtLfmq09OH2jfgZf78EIcCDclwP1dbGMc80YgLqOKSm7/XrGm1AfokB8cDVVk=

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
